services:
  laravel:
    restart: unless-stopped
    container_name: laravelapp
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8080:80"
    networks:
      - laranext
    depends_on:
      - database

  database:
    restart: unless-stopped
    image: mariadb:lts-jammy
    volumes:
      - v-database:/var/lib/mysql
    environment:
      MARIADB_DATABASE: laranext
      MARIADB_USER: root
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
    networks:
      - laranext

  frontend:
    restart: unless-stopped
    image: node:18
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
        - "3000:3000"
    command: sh -c "npm install && npm run dev"
    networks:
      - laranext

volumes:
  v-database:


networks:
  laranext:
    driver: bridge